version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: unit test
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test